name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: npm install

      - name: Build the Application
        run: npm run build

      - name: node main.js
        run: |
          # Replace the commands below with your actual deployment commands
          # For example, if you use SSH to deploy to your server
          ssh user@your-server 'https://github.com/7okesh/whatsapp-http-api-core && git pull && npm install && pm2 start'

